apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
      matchLabels:
        app.kubernetes.io/name: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app
    spec:
      containers:
        - name: app
          image: jalopezb/kubernetes-app:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  labels:
    service-label-key: app-service
  name: service-name
spec:
  type: ClusterIP
  ports:
  - name: service-port-name
    port: 80
    protocol: TCP
  selector:
    app.kubernetes.io/name: app
---

apiVersion: v1
kind: Service
metadata:
  labels:
    service-label-key: lb-service
  name: service-name-loadbalancer
spec:
  type: LoadBalancer
  ports:
  - name: service-port-name
    port: 80
    protocol: TCP
  selector:
    app.kubernetes.io/name: app
